// scripts/generateI18nTypes.js
const fs = require('fs');
const path = require('path');

// 1. נתיבים מתוקנים
// הנתיב לתיקיית התרגום נמצא בתיקיית messages בבסיס הפרויקט
const I18N_DIR = path.join(__dirname, '../messages');

// קובץ הטיפוסים שייווצר. נשמור אותו בתיקייה 'types' בתוך src
const OUTPUT_FILE = path.join(__dirname, '../src/types/i18n-keys.ts');

// 2. קריאת קובץ התרגום הראשי (נשתמש ב-en.json כבסיס לטיפוסים)
function generateTranslationKeys() {
    console.log('Generating i18n TypeScript types...');

    // הנתיב לקובץ ה-JSON
    const enPath = path.join(I18N_DIR, 'en.json');

    if (!fs.existsSync(enPath)) {
        console.error(`Error: Translation file not found at ${enPath}`);
        console.error(`Please ensure your translation files exist in the 'messages' folder.`);
        return;
    }

    try {
        const messages = JSON.parse(fs.readFileSync(enPath, 'utf8'));

        // חילוץ המפתחות
        const keys = Object.keys(messages);

        // יצירת ה-Literal Union Type
        const unionType = keys.map(key => `'${key}'`).join(' | ');

        // תוכן קובץ הטיפוסים הסופי
        const tsContent = `// This file is auto-generated by a script. Do not modify manually.
// Run 'npm run i18n:generate-types' to update.

/**
 * כל מפתחות התרגום הקיימים בפרויקט שלך (Literal Union Type).
 * מופק מתוך קובץ התרגום הראשי (messages/en.json).
 */
export type TranslationKeys = ${unionType || 'never'};
`;

        // לוודא שתיקיית ה-types קיימת
        const outputDir = path.dirname(OUTPUT_FILE);
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        // כתיבת הקובץ
        fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8');
        console.log(`✅ Successfully generated ${keys.length} keys to ${OUTPUT_FILE}`);

    } catch (error) {
        console.error("Failed to generate translation types:", error);
    }
}

generateTranslationKeys();